repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: gitlint
        name: gitlint
        language: python
        entry: gitlint
        args: [--staged, --msg-filename]
        stages: [commit-msg]
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    -   id: black
        language: python
        args: [--skip-string-normalization]
-   repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocesor.enabled=True --inplace
