repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: gitlint
        name: gitlint
        language: python
        entry: gitlint
        args: [--staged, --msg-filename]
        stages: [commit-msg]


